-- Run this once in the Supabase SQL editor to create the Inquiries tab's table.

create table if not exists venue_inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text,
  phone text,
  event_type text,
  event_date date,
  guest_count int,
  message text,
  status text not null default 'New',
  notes text
);

alter table venue_inquiries enable row level security;

create policy "venue_inquiries_select" on venue_inquiries
  for select using (true);

create policy "venue_inquiries_insert" on venue_inquiries
  for insert with check (true);

create policy "venue_inquiries_update" on venue_inquiries
  for update using (true);

create policy "venue_inquiries_delete" on venue_inquiries
  for delete using (true);
