-- Wedding inquiry automation: tour scheduling + staged email pipeline.
-- Run once against the shared project. Safe to re-run (idempotent).

-- ── Pipeline tracking columns on venue_inquiries ───────────────────────────
-- Reuses the existing `status` text column as the pipeline stage. New values:
-- New | Initial Inquiry Sent | Follow Up Sent | Final Follow Up Sent |
-- Tour Scheduled | Toured - Docs Sent | Booked | Declined | Archive
alter table venue_inquiries add column if not exists initial_sent_at timestamptz;
alter table venue_inquiries add column if not exists follow_up_sent_at timestamptz;
alter table venue_inquiries add column if not exists final_follow_up_sent_at timestamptz;

-- ── Tour hosts (Jen, Sierra, ...) ───────────────────────────────────────────
create table if not exists venue_tour_hosts (
  id     bigint generated by default as identity primary key,
  name   text not null unique,
  email  text,
  active boolean not null default true
);

insert into venue_tour_hosts (name) values ('Jen'), ('Sierra')
  on conflict (name) do nothing;

-- ── Open availability slots staff publish for self-scheduling ─────────────
create table if not exists venue_tour_availability (
  id         bigint generated by default as identity primary key,
  host_id    bigint not null references venue_tour_hosts(id) on delete cascade,
  slot_start timestamptz not null,
  slot_end   timestamptz not null,
  is_booked  boolean not null default false,
  created_at timestamptz not null default now()
);

-- ── Booked tours ────────────────────────────────────────────────────────
create table if not exists venue_tours (
  id                    bigint generated by default as identity primary key,
  inquiry_id            bigint not null references venue_inquiries(id) on delete cascade,
  host_id               bigint references venue_tour_hosts(id),
  availability_id       bigint references venue_tour_availability(id),
  slot_start            timestamptz not null,
  slot_end              timestamptz not null,
  status                text not null default 'Scheduled', -- Scheduled | Completed | Cancelled
  confirmation_sent_at  timestamptz,
  reminder_24h_sent_at  timestamptz,
  reminder_1h_sent_at   timestamptz,
  docs_sent_at          timestamptz,
  created_at            timestamptz not null default now()
);

-- ── Email copy, editable via SQL (no redeploy needed to change wording) ───
create table if not exists venue_email_templates (
  id         bigint generated by default as identity primary key,
  key        text not null unique,
  subject    text not null,
  body       text not null,
  updated_at timestamptz not null default now()
);

insert into venue_email_templates (key, subject, body) values
  ('initial_inquiry', '[PLACEHOLDER SUBJECT] Thank you for your inquiry, {{name}}!',
   '[PLACEHOLDER COPY — replace with real Information & Pricing Guide text]\n\nHi {{name}},\n\nThank you for your interest in North Star House! Attached is our Information & Pricing Guide.\n\nYou can self-schedule a tour with Jen or Sierra here: {{scheduling_link}}\n\nWarmly,\nNorth Star House'),
  ('follow_up_48h', '[PLACEHOLDER SUBJECT] Still thinking about a tour, {{name}}?',
   '[PLACEHOLDER COPY]\n\nHi {{name}},\n\nJust checking in — would you like to schedule a tour? {{scheduling_link}}\n\nHappy to answer any questions!'),
  ('final_follow_up_30d', '[PLACEHOLDER SUBJECT] Last check-in, {{name}}',
   '[PLACEHOLDER COPY]\n\nHi {{name}},\n\nWe haven''t heard back — if you''re still interested in touring North Star House, you can schedule here: {{scheduling_link}}'),
  ('tour_confirmation', '[PLACEHOLDER SUBJECT] Your tour is confirmed — {{tour_date}} at {{tour_time}}',
   '[PLACEHOLDER COPY — replace with real arrival instructions]\n\nHi {{name}},\n\nYour tour with {{host_name}} is confirmed for {{tour_date}} at {{tour_time}}.\n\n[Arrival instructions here]'),
  ('tour_reminder_24h', '[PLACEHOLDER SUBJECT] Reminder: your tour is tomorrow',
   '[PLACEHOLDER COPY]\n\nHi {{name}},\n\nJust a reminder that your tour with {{host_name}} is tomorrow, {{tour_date}} at {{tour_time}}.'),
  ('tour_reminder_1h', '[PLACEHOLDER SUBJECT] Reminder: your tour is in 1 hour',
   '[PLACEHOLDER COPY]\n\nHi {{name}},\n\nYour tour with {{host_name}} starts in about an hour, at {{tour_time}}.'),
  ('toured_docs', '[PLACEHOLDER SUBJECT] Thanks for touring North Star House!',
   '[PLACEHOLDER COPY — replace with real guidebook + pre-booking form links]\n\nHi {{name}},\n\nThank you for touring with {{host_name}}! Here is our digital guidebook: {{guidebook_link}}\n\nIf you''d like to move forward, you can submit our pre-booking form here: {{prebooking_link}}')
on conflict (key) do nothing;

-- ── RLS: same permissive model as venue_inquiries (app-layer auth gates access) ──
alter table venue_tour_hosts       enable row level security;
alter table venue_tour_availability enable row level security;
alter table venue_tours            enable row level security;
alter table venue_email_templates  enable row level security;

create policy "venue_tour_hosts_select" on venue_tour_hosts for select using (true);
create policy "venue_tour_hosts_insert" on venue_tour_hosts for insert with check (true);
create policy "venue_tour_hosts_update" on venue_tour_hosts for update using (true);

create policy "venue_tour_availability_select" on venue_tour_availability for select using (true);
create policy "venue_tour_availability_insert" on venue_tour_availability for insert with check (true);
create policy "venue_tour_availability_update" on venue_tour_availability for update using (true);
create policy "venue_tour_availability_delete" on venue_tour_availability for delete using (true);

create policy "venue_tours_select" on venue_tours for select using (true);
create policy "venue_tours_insert" on venue_tours for insert with check (true);
create policy "venue_tours_update" on venue_tours for update using (true);

create policy "venue_email_templates_select" on venue_email_templates for select using (true);
create policy "venue_email_templates_update" on venue_email_templates for update using (true);
